nodes:
  - 1:
      - button:
          - address: 0x20
          - port: 5
      - led:
          - address: 0x20
          - port: 4
  - 2:
    - button:
        - address: 0x20
        - port: 6
    - led:
        - address: 0x20
        - port: 7