nodes:
  - 1:
      - button:
          - address: 45x4
          - port: 7
      - led:
          - address: 21x4
          - port: 0
  - 2:
      - button:
          - address: 48x4
          - port: 3
      - led:
          - address: 25x4
          - port: 1

